import { renderToStaticMarkup } from 'react-dom/server';
import { expect, it, vi } from 'vitest';
// A string action stands in for the URL generated by Next's Server Action encoder.
// Keep the real LogoutButton/form; the no-JS E2E covers the framework encoder.
vi.mock('@/actions/account', () => ({ signOutAction: '/test-sign-out' }));
vi.mock('@/components/ui/sidebar', () => ({ SidebarTrigger: () => null }));
vi.mock('@/components/business/admin/AdminBreadcrumb', () => ({ AdminBreadcrumb: () => null }));
vi.mock('@/components/business/admin/UserMenu', () => ({ UserMenu: () => <span>用户菜单</span> }));
vi.mock('@/components/business/admin/ThemeToggle', () => ({ ThemeToggle: () => null }));
import { AdminHeader } from '@/components/business/admin/AdminHeader';
it('renders a native logout form with action and submit button inside noscript', () => {
  const html = renderToStaticMarkup(<AdminHeader displayName="管理员" roleLabel="管理员" environmentLabel="production" />);
  const fallback = html.match(/<noscript>([\s\S]*?)<\/noscript>/)?.[1];
  expect(fallback).toMatch(/<form[^>]*action="\/test-sign-out"/);
  expect(fallback).toMatch(/<button[^>]*type="submit"[^>]*>退出登录<\/button>/);
  expect(html).toContain('用户菜单');
});
