import { describe, expect, it } from 'vitest';
import {
  BackgroundJobStatus,
  BillStatus,
  DesignBundleStatus,
  NotificationStatus,
  OrderChangeRequestStatus,
  OrderExportStatus,
  OrderStatus,
  OutsourceStatus,
  PurchaseOrderStatus,
  PurchaseReceiptStatus,
  SalaryPeriodStatus,
  ShipmentStatus,
  TaskStatus,
} from '@/generated/prisma/enums';
import {
  BACKGROUND_JOB_STATUS_REGISTRY,
  BILL_STATUS_REGISTRY,
  CUSTOMER_PRICE_BOOK_VERSION_STATUS,
  CUSTOMER_PRICE_BOOK_VERSION_STATUS_REGISTRY,
  DESIGN_BUNDLE_DISPLAY_STATUS,
  DESIGN_BUNDLE_DISPLAY_STATUS_REGISTRY,
  NOTIFICATION_STATUS_REGISTRY,
  ORDER_CHANGE_REQUEST_STATUS_REGISTRY,
  ORDER_EXPORT_STATUS_REGISTRY,
  ORDER_STATUS_REGISTRY,
  OUTSOURCE_STATUS_REGISTRY,
  PAYMENT_STATUS_REGISTRY,
  PRODUCTION_TASK_STATUS_REGISTRY,
  PURCHASE_ORDER_STATUS_REGISTRY,
  PURCHASE_RECEIPT_STATUS_REGISTRY,
  SALARY_PERIOD_DISPLAY_STATUS,
  SALARY_PERIOD_STATUS_REGISTRY,
  SHIPMENT_STATUS_REGISTRY,
  notificationStatusDefinition,
  paymentStatusDefinition,
  salaryPeriodStatusDefinition,
  statusFilterLabel,
} from '../status-registry';

describe('status registry', () => {
  it('exhaustively covers persisted status enums', () => {
    expect(Object.keys(ORDER_STATUS_REGISTRY).sort()).toEqual(
      Object.values(OrderStatus).sort(),
    );
    expect(Object.keys(BILL_STATUS_REGISTRY).sort()).toEqual(
      Object.values(BillStatus).sort(),
    );
    expect(Object.keys(NOTIFICATION_STATUS_REGISTRY).sort()).toEqual(
      Object.values(NotificationStatus).sort(),
    );
    expect(Object.keys(BACKGROUND_JOB_STATUS_REGISTRY).sort()).toEqual(
      Object.values(BackgroundJobStatus).sort(),
    );
    expect(Object.keys(ORDER_CHANGE_REQUEST_STATUS_REGISTRY).sort()).toEqual(
      Object.values(OrderChangeRequestStatus).sort(),
    );
    expect(Object.keys(OUTSOURCE_STATUS_REGISTRY).sort()).toEqual(
      Object.values(OutsourceStatus).sort(),
    );
    expect(Object.keys(PRODUCTION_TASK_STATUS_REGISTRY).sort()).toEqual(
      Object.values(TaskStatus).sort(),
    );
    expect(Object.keys(SHIPMENT_STATUS_REGISTRY).sort()).toEqual(
      Object.values(ShipmentStatus).sort(),
    );
    expect(Object.keys(PURCHASE_ORDER_STATUS_REGISTRY).sort()).toEqual(
      Object.values(PurchaseOrderStatus).sort(),
    );
    expect(Object.keys(PURCHASE_RECEIPT_STATUS_REGISTRY).sort()).toEqual(
      Object.values(PurchaseReceiptStatus).sort(),
    );
    expect(Object.keys(ORDER_EXPORT_STATUS_REGISTRY).sort()).toEqual(
      Object.values(OrderExportStatus).sort(),
    );
    expect(
      Object.values(DesignBundleStatus).every(
        (status) => status in DESIGN_BUNDLE_DISPLAY_STATUS_REGISTRY,
      ),
    ).toBe(true);
    expect(Object.keys(DESIGN_BUNDLE_DISPLAY_STATUS_REGISTRY).sort()).toEqual(
      Object.values(DESIGN_BUNDLE_DISPLAY_STATUS).sort(),
    );
    expect(
      Object.keys(CUSTOMER_PRICE_BOOK_VERSION_STATUS_REGISTRY).sort(),
    ).toEqual(Object.values(CUSTOMER_PRICE_BOOK_VERSION_STATUS).sort());
  });

  it('does not render queued, running, or unresolved work as danger', () => {
    expect(ORDER_STATUS_REGISTRY[OrderStatus.PENDING_FACTORY]).toMatchObject({
      label: '待工厂确认',
      tone: 'info',
    });
    expect(ORDER_STATUS_REGISTRY[OrderStatus.SUBMITTED].label).toBe(
      '待工厂确认',
    );
    expect(ORDER_STATUS_REGISTRY[OrderStatus.IN_PRODUCTION].tone).toBe('info');
    expect(BILL_STATUS_REGISTRY[BillStatus.ISSUED].tone).toBe('warning');
    expect(
      NOTIFICATION_STATUS_REGISTRY[NotificationStatus.SENDING].tone,
    ).toBe('info');
    expect(
      NOTIFICATION_STATUS_REGISTRY[NotificationStatus.RETRYING].tone,
    ).toBe('warning');
    expect(
      NOTIFICATION_STATUS_REGISTRY[NotificationStatus.UNKNOWN].tone,
    ).toBe('warning');
    expect(
      BACKGROUND_JOB_STATUS_REGISTRY[BackgroundJobStatus.PENDING].tone,
    ).toBe('neutral');
    expect(
      BACKGROUND_JOB_STATUS_REGISTRY[BackgroundJobStatus.RUNNING].tone,
    ).toBe('info');
    expect(
      ORDER_CHANGE_REQUEST_STATUS_REGISTRY[
        OrderChangeRequestStatus.PENDING
      ].tone,
    ).toBe('warning');
    expect(OUTSOURCE_STATUS_REGISTRY[OutsourceStatus.SENT].tone).toBe('info');
    expect(OUTSOURCE_STATUS_REGISTRY[OutsourceStatus.IN_PROGRESS].tone).toBe(
      'info',
    );
    expect(PRODUCTION_TASK_STATUS_REGISTRY[TaskStatus.PENDING].tone).toBe(
      'neutral',
    );
    expect(SHIPMENT_STATUS_REGISTRY[ShipmentStatus.PLANNED].tone).toBe(
      'warning',
    );
    expect(
      PURCHASE_ORDER_STATUS_REGISTRY[PurchaseOrderStatus.ORDERED].tone,
    ).toBe('info');
    expect(
      PURCHASE_ORDER_STATUS_REGISTRY[
        PurchaseOrderStatus.PARTIALLY_RECEIVED
      ].tone,
    ).toBe('warning');
    expect(
      ORDER_EXPORT_STATUS_REGISTRY[OrderExportStatus.PENDING].tone,
    ).toBe('info');
    expect(
      DESIGN_BUNDLE_DISPLAY_STATUS_REGISTRY[
        DESIGN_BUNDLE_DISPLAY_STATUS.PENDING
      ].tone,
    ).toBe('info');
    expect(
      ORDER_EXPORT_STATUS_REGISTRY[OrderExportStatus.EXPIRED].tone,
    ).toBe('neutral');
    expect(
      DESIGN_BUNDLE_DISPLAY_STATUS_REGISTRY[
        DESIGN_BUNDLE_DISPLAY_STATUS.EXPIRED
      ].tone,
    ).toBe('neutral');
    expect(
      DESIGN_BUNDLE_DISPLAY_STATUS_REGISTRY[
        DESIGN_BUNDLE_DISPLAY_STATUS.MOCK
      ].tone,
    ).toBe('neutral');
    expect(
      CUSTOMER_PRICE_BOOK_VERSION_STATUS_REGISTRY[
        CUSTOMER_PRICE_BOOK_VERSION_STATUS.SCHEDULED
      ].tone,
    ).toBe('info');
  });

  it('reserves danger for failed, cancelled, dead, or exhausted states', () => {
    expect(
      NOTIFICATION_STATUS_REGISTRY[NotificationStatus.FAILED].tone,
    ).toBe('danger');
    expect(
      notificationStatusDefinition(NotificationStatus.RETRYING, {
        hasDeadLetterJob: true,
      }),
    ).toMatchObject({ label: '重试耗尽', tone: 'danger' });
    expect(
      BACKGROUND_JOB_STATUS_REGISTRY[BackgroundJobStatus.DEAD].tone,
    ).toBe('danger');
    expect(
      BACKGROUND_JOB_STATUS_REGISTRY[BackgroundJobStatus.CANCELLED].tone,
    ).toBe('danger');
    expect(
      ORDER_CHANGE_REQUEST_STATUS_REGISTRY[
        OrderChangeRequestStatus.REJECTED
      ].tone,
    ).toBe('danger');
    expect(
      OUTSOURCE_STATUS_REGISTRY[OutsourceStatus.CANCELLED].tone,
    ).toBe('danger');
    expect(
      PRODUCTION_TASK_STATUS_REGISTRY[TaskStatus.CANCELLED].tone,
    ).toBe('danger');
    expect(
      PURCHASE_ORDER_STATUS_REGISTRY[PurchaseOrderStatus.CANCELLED].tone,
    ).toBe('danger');
    expect(
      PURCHASE_RECEIPT_STATUS_REGISTRY[PurchaseReceiptStatus.CANCELLED].tone,
    ).toBe('danger');
    expect(
      ORDER_EXPORT_STATUS_REGISTRY[OrderExportStatus.FAILED].tone,
    ).toBe('danger');
    expect(
      DESIGN_BUNDLE_DISPLAY_STATUS_REGISTRY[
        DESIGN_BUNDLE_DISPLAY_STATUS.FAILED
      ].tone,
    ).toBe('danger');
  });

  it('keeps completed and current domain work positive', () => {
    expect(
      ORDER_CHANGE_REQUEST_STATUS_REGISTRY[
        OrderChangeRequestStatus.APPROVED
      ].tone,
    ).toBe('success');
    expect(OUTSOURCE_STATUS_REGISTRY[OutsourceStatus.RECEIVED].tone).toBe(
      'success',
    );
    expect(PRODUCTION_TASK_STATUS_REGISTRY[TaskStatus.COMPLETED].tone).toBe(
      'success',
    );
    expect(SHIPMENT_STATUS_REGISTRY[ShipmentStatus.SHIPPED].tone).toBe(
      'success',
    );
    expect(
      PURCHASE_ORDER_STATUS_REGISTRY[PurchaseOrderStatus.RECEIVED].tone,
    ).toBe('success');
    expect(
      PURCHASE_RECEIPT_STATUS_REGISTRY[PurchaseReceiptStatus.POSTED].tone,
    ).toBe('success');
    expect(
      ORDER_EXPORT_STATUS_REGISTRY[OrderExportStatus.READY].tone,
    ).toBe('success');
    expect(
      DESIGN_BUNDLE_DISPLAY_STATUS_REGISTRY[
        DESIGN_BUNDLE_DISPLAY_STATUS.READY
      ].tone,
    ).toBe('success');
    expect(
      CUSTOMER_PRICE_BOOK_VERSION_STATUS_REGISTRY[
        CUSTOMER_PRICE_BOOK_VERSION_STATUS.CURRENT
      ].tone,
    ).toBe('success');
  });

  it('uses consistent salary period and payment semantics', () => {
    expect(paymentStatusDefinition(true)).toEqual(
      PAYMENT_STATUS_REGISTRY.PAID,
    );
    expect(paymentStatusDefinition(false)).toEqual(
      PAYMENT_STATUS_REGISTRY.UNPAID,
    );
    expect(
      salaryPeriodStatusDefinition(SalaryPeriodStatus.IN_PROGRESS, {
        readyToSettle: true,
      }),
    ).toEqual(
      SALARY_PERIOD_STATUS_REGISTRY[
        SALARY_PERIOD_DISPLAY_STATUS.READY_TO_SETTLE
      ],
    );
    expect(
      SALARY_PERIOD_STATUS_REGISTRY[
        SALARY_PERIOD_DISPLAY_STATUS.READY_TO_SETTLE
      ].tone,
    ).toBe('warning');
  });

  it('keeps precise filter wording without duplicating local label maps', () => {
    expect(
      statusFilterLabel(PRODUCTION_TASK_STATUS_REGISTRY[TaskStatus.PENDING]),
    ).toBe('待生产');
    expect(
      statusFilterLabel(
        PRODUCTION_TASK_STATUS_REGISTRY[TaskStatus.IN_PROGRESS],
      ),
    ).toBe('生产中');
    expect(
      statusFilterLabel(OUTSOURCE_STATUS_REGISTRY[OutsourceStatus.SENT]),
    ).toBe('已发送');
    expect(
      statusFilterLabel(OUTSOURCE_STATUS_REGISTRY[OutsourceStatus.RECEIVED]),
    ).toBe('已收货');
    expect(
      statusFilterLabel(SHIPMENT_STATUS_REGISTRY[ShipmentStatus.PLANNED]),
    ).toBe('待发货');
  });
});
