import { Role } from '../../generated/prisma/enums';
import type { Permission } from '../auth/permissions-dict';

// 受控的图标名集合。新增图标时同时更新 AppSidebar 的 ICONS map。
export type IconName =
  | 'LayoutDashboard'
  | 'ClipboardList'
  | 'PlusCircle'
  | 'Wallet'
  | 'CalendarDays'
  | 'Calculator'
  | 'BookOpen'
  | 'Users'
  | 'CalendarClock'
  | 'PackageOpen'
  | 'Boxes'
  | 'Clock'
  | 'FileText'
  | 'TrendingUp'
  | 'Sparkles'
  | 'Bell'
  | 'FileArchive'
  | 'Database'
  | 'Settings';

export type AdminModuleStatus = 'implemented' | 'placeholder';

export type AdminMenuSection =
  | 'dashboard'
  | 'workflow'
  | 'finance'
  | 'dictionary'
  | 'operations'
  | 'account';

export type AdminModuleMetadata = {
  id: string;
  label: string;
  routeBase: string;
  activeRouteBase?: string;
  iconName: IconName;
  breadcrumbLabel: string;
  menuSection: AdminMenuSection;
  status: AdminModuleStatus;
  menuOrder: number;
  menuRoles: readonly Role[];
  requiredPermission?: Permission;
  roles?: readonly Role[];
};

export const ADMIN_MODULES: readonly AdminModuleMetadata[] = [
  {
    id: 'owner.dashboard',
    label: 'Dashboard',
    routeBase: '/owner',
    iconName: 'LayoutDashboard',
    breadcrumbLabel: 'Dashboard',
    menuSection: 'dashboard',
    status: 'implemented',
    menuOrder: 10,
    menuRoles: [Role.ADMIN],
    roles: [Role.ADMIN],
  },
  {
    id: 'owner.orders',
    label: '工单',
    routeBase: '/orders',
    iconName: 'ClipboardList',
    breadcrumbLabel: '工单',
    menuSection: 'workflow',
    status: 'implemented',
    menuOrder: 20,
    menuRoles: [Role.ADMIN],
    requiredPermission: 'order:view:all',
  },
  {
    id: 'owner.purchases',
    label: '采购单',
    routeBase: '/owner/purchases',
    iconName: 'ClipboardList',
    breadcrumbLabel: '采购单',
    menuSection: 'workflow',
    status: 'implemented',
    menuOrder: 25,
    menuRoles: [Role.ADMIN],
    requiredPermission: 'purchase:manage',
  },
  {
    id: 'owner.orderChanges',
    label: '工单修改申请',
    routeBase: '/owner/order-changes',
    iconName: 'FileText',
    breadcrumbLabel: '工单修改申请',
    menuSection: 'workflow',
    status: 'implemented',
    menuOrder: 27,
    menuRoles: [Role.ADMIN],
    requiredPermission: 'order:change:review',
  },
  {
    id: 'owner.bills',
    label: '账单',
    routeBase: '/owner/bills',
    iconName: 'Wallet',
    breadcrumbLabel: '账单',
    menuSection: 'finance',
    status: 'implemented',
    menuOrder: 30,
    menuRoles: [Role.ADMIN],
    requiredPermission: 'bill:view:all',
  },
  {
    id: 'owner.salary',
    label: '薪资总览',
    routeBase: '/owner/salary',
    iconName: 'Calculator',
    breadcrumbLabel: '薪资总览',
    menuSection: 'finance',
    status: 'implemented',
    menuOrder: 40,
    menuRoles: [Role.ADMIN],
    requiredPermission: 'salary:view:all',
  },
  {
    id: 'owner.salary.daily',
    label: '计件工资',
    routeBase: '/owner/salary/daily',
    iconName: 'Calculator',
    breadcrumbLabel: '计件工资',
    menuSection: 'finance',
    status: 'implemented',
    menuOrder: 50,
    menuRoles: [Role.ADMIN],
    requiredPermission: 'salary:view:all',
  },
  {
    id: 'owner.salary.piecework-rules',
    label: '开机师傅计件规则',
    routeBase: '/owner/salary/piecework-rules',
    iconName: 'Calculator',
    breadcrumbLabel: '计件规则',
    menuSection: 'finance',
    status: 'implemented',
    menuOrder: 55,
    menuRoles: [Role.ADMIN],
    requiredPermission: 'salary:rule:manage',
  },
  {
    id: 'owner.salary.rules',
    label: '员工工资规则',
    routeBase: '/owner/salary/rules',
    iconName: 'Calculator',
    breadcrumbLabel: '员工工资规则',
    menuSection: 'finance',
    status: 'implemented',
    menuOrder: 57,
    menuRoles: [Role.ADMIN],
    requiredPermission: 'salary:rule:manage',
  },
  {
    id: 'owner.salary.cs',
    label: '客服周期',
    routeBase: '/owner/salary/cs',
    iconName: 'CalendarClock',
    breadcrumbLabel: '客服周期',
    menuSection: 'finance',
    status: 'implemented',
    menuOrder: 60,
    menuRoles: [Role.ADMIN],
    requiredPermission: 'salary:view:all',
  },
  {
    id: 'owner.salary.hourly',
    label: '时薪工月结',
    routeBase: '/owner/salary/hourly',
    iconName: 'Clock',
    breadcrumbLabel: '时薪工月结',
    menuSection: 'finance',
    status: 'implemented',
    menuOrder: 70,
    menuRoles: [Role.ADMIN],
    requiredPermission: 'salary:view:all',
  },
  {
    id: 'owner.parties',
    label: '客户/供应商',
    routeBase: '/owner/parties',
    iconName: 'Users',
    breadcrumbLabel: '客户/供应商',
    menuSection: 'dictionary',
    status: 'implemented',
    menuOrder: 75,
    menuRoles: [Role.ADMIN],
    requiredPermission: 'party:manage',
  },
  {
    id: 'owner.crafts',
    label: '工艺字典',
    routeBase: '/owner/crafts',
    iconName: 'BookOpen',
    breadcrumbLabel: '工艺字典',
    menuSection: 'dictionary',
    status: 'implemented',
    menuOrder: 80,
    menuRoles: [Role.ADMIN],
    requiredPermission: 'dict:craft:manage',
  },
  {
    id: 'owner.products',
    label: '产品字典',
    routeBase: '/owner/products',
    iconName: 'PackageOpen',
    breadcrumbLabel: '产品字典',
    menuSection: 'dictionary',
    status: 'implemented',
    menuOrder: 90,
    menuRoles: [Role.ADMIN],
    requiredPermission: 'dict:product:manage',
  },
  {
    id: 'owner.productCategories',
    label: '产品分类',
    routeBase: '/owner/product-categories',
    iconName: 'PackageOpen',
    breadcrumbLabel: '产品分类',
    menuSection: 'dictionary',
    status: 'implemented',
    menuOrder: 100,
    menuRoles: [Role.ADMIN],
    requiredPermission: 'dict:product:manage',
  },
  {
    id: 'owner.prices.external-sales.items',
    label: '外部销售收费',
    routeBase: '/owner/prices/external-sales/items',
    activeRouteBase: '/owner/prices/external-sales',
    iconName: 'FileText',
    breadcrumbLabel: '外部销售收费',
    menuSection: 'dictionary',
    status: 'implemented',
    menuOrder: 105,
    menuRoles: [Role.ADMIN],
    requiredPermission: 'dict:price:manage',
  },
  {
    id: 'owner.prices',
    label: '内部报价（低频）',
    routeBase: '/owner/prices',
    iconName: 'FileText',
    breadcrumbLabel: '内部报价',
    menuSection: 'dictionary',
    status: 'implemented',
    menuOrder: 110,
    menuRoles: [Role.ADMIN],
    requiredPermission: 'dict:price:manage',
  },
  {
    id: 'owner.boms',
    label: 'BOM/用料',
    routeBase: '/owner/boms',
    iconName: 'FileText',
    breadcrumbLabel: 'BOM/用料',
    menuSection: 'dictionary',
    status: 'implemented',
    menuOrder: 115,
    menuRoles: [Role.ADMIN],
    requiredPermission: 'bom:manage',
  },
  {
    id: 'owner.materials',
    label: '物料',
    routeBase: '/owner/materials',
    iconName: 'Boxes',
    breadcrumbLabel: '物料',
    menuSection: 'dictionary',
    status: 'implemented',
    menuOrder: 120,
    menuRoles: [Role.ADMIN],
    requiredPermission: 'material:manage',
  },
  {
    id: 'owner.warehouses',
    label: '仓库/库位',
    routeBase: '/owner/warehouses',
    iconName: 'Boxes',
    breadcrumbLabel: '仓库/库位',
    menuSection: 'dictionary',
    status: 'implemented',
    menuOrder: 125,
    menuRoles: [Role.ADMIN],
    requiredPermission: 'warehouse:manage',
  },
  {
    id: 'owner.accounts',
    label: '用户管理',
    routeBase: '/owner/accounts',
    iconName: 'Users',
    breadcrumbLabel: '用户管理',
    menuSection: 'account',
    status: 'implemented',
    menuOrder: 130,
    menuRoles: [Role.ADMIN],
    requiredPermission: 'account:manage',
  },
  {
    id: 'owner.notifications',
    label: '推送配置',
    routeBase: '/owner/notifications',
    iconName: 'Bell',
    breadcrumbLabel: '推送配置',
    menuSection: 'operations',
    status: 'implemented',
    menuOrder: 140,
    menuRoles: [Role.ADMIN],
    requiredPermission: 'notification:config',
  },
  {
    id: 'owner.settings',
    label: '系统设置',
    routeBase: '/owner/settings',
    iconName: 'Settings',
    breadcrumbLabel: '系统设置',
    menuSection: 'operations',
    status: 'implemented',
    menuOrder: 135,
    menuRoles: [Role.ADMIN],
    requiredPermission: 'setting:manage',
  },
  {
    id: 'owner.pigsty',
    label: 'Pigsty 运维',
    routeBase: '/owner/pigsty',
    iconName: 'Database',
    breadcrumbLabel: 'Pigsty 运维',
    menuSection: 'operations',
    status: 'implemented',
    menuOrder: 150,
    menuRoles: [Role.ADMIN],
    requiredPermission: 'ops:pigsty:view',
  },
  {
    id: 'owner.backgroundJobs',
    label: '后台任务',
    routeBase: '/owner/background-jobs',
    iconName: 'Clock',
    breadcrumbLabel: '后台任务',
    menuSection: 'operations',
    status: 'implemented',
    menuOrder: 145,
    menuRoles: [Role.ADMIN],
    requiredPermission: 'ops:jobs:manage',
  },
  {
    id: 'foreman.scheduling',
    label: '排产',
    routeBase: '/foreman/scheduling',
    iconName: 'CalendarDays',
    breadcrumbLabel: '排产',
    menuSection: 'workflow',
    status: 'implemented',
    menuOrder: 30,
    menuRoles: [Role.ADMIN],
    requiredPermission: 'order:schedule',
  },
  {
    id: 'foreman.outsource',
    label: '外协',
    routeBase: '/foreman/outsource',
    iconName: 'PackageOpen',
    breadcrumbLabel: '外协',
    menuSection: 'workflow',
    status: 'implemented',
    menuOrder: 40,
    menuRoles: [Role.ADMIN],
    requiredPermission: 'outsource:manage',
  },
  {
    id: 'foreman.materials',
    label: '车间用料',
    routeBase: '/foreman/materials',
    iconName: 'Boxes',
    breadcrumbLabel: '车间用料',
    menuSection: 'workflow',
    status: 'implemented',
    menuOrder: 45,
    menuRoles: [Role.ADMIN],
    requiredPermission: 'material:manage',
  },
  {
    id: 'foreman.attendance',
    label: '工时录入',
    routeBase: '/foreman/attendance',
    iconName: 'Clock',
    breadcrumbLabel: '工时录入',
    menuSection: 'workflow',
    status: 'implemented',
    menuOrder: 50,
    menuRoles: [Role.ADMIN],
    requiredPermission: 'task:assign',
  },
  {
    id: 'foreman.cdr',
    label: 'CDR 汇总',
    routeBase: '/foreman/cdr',
    iconName: 'FileArchive',
    breadcrumbLabel: 'CDR 汇总',
    menuSection: 'operations',
    status: 'implemented',
    menuOrder: 160,
    menuRoles: [Role.ADMIN],
    requiredPermission: 'design:bundle:create',
  },
  {
    id: 'sales.dashboard',
    label: '我的 Dashboard',
    routeBase: '#',
    iconName: 'LayoutDashboard',
    breadcrumbLabel: '我的 Dashboard',
    menuSection: 'dashboard',
    status: 'placeholder',
    menuOrder: 10,
    menuRoles: [Role.SALES],
    roles: [Role.SALES],
  },
  {
    id: 'sales.orders.new',
    label: '创建工单',
    routeBase: '/orders/new',
    iconName: 'PlusCircle',
    breadcrumbLabel: '创建工单',
    menuSection: 'workflow',
    status: 'implemented',
    menuOrder: 20,
    menuRoles: [Role.SALES],
    requiredPermission: 'order:create',
  },
  {
    id: 'sales.orders',
    label: '我的工单',
    routeBase: '/orders',
    iconName: 'ClipboardList',
    breadcrumbLabel: '我的工单',
    menuSection: 'workflow',
    status: 'implemented',
    menuOrder: 30,
    menuRoles: [Role.SALES],
    requiredPermission: 'order:view:self',
  },
  {
    id: 'sales.bills',
    label: '我的账单',
    routeBase: '/sales/bills',
    iconName: 'Wallet',
    breadcrumbLabel: '我的账单',
    menuSection: 'finance',
    status: 'implemented',
    menuOrder: 40,
    menuRoles: [Role.SALES],
    requiredPermission: 'bill:view:self',
  },
  {
    id: 'sales.quote',
    label: '报价查询',
    routeBase: '/sales/quote',
    iconName: 'FileText',
    breadcrumbLabel: '报价查询',
    menuSection: 'workflow',
    status: 'implemented',
    menuOrder: 50,
    menuRoles: [Role.SALES],
    requiredPermission: 'order:create',
  },
  {
    id: 'cs.dashboard',
    label: '我的 Dashboard',
    routeBase: '#',
    iconName: 'LayoutDashboard',
    breadcrumbLabel: '我的 Dashboard',
    menuSection: 'dashboard',
    status: 'placeholder',
    menuOrder: 10,
    menuRoles: [Role.CUSTOMER_SERVICE],
    roles: [Role.CUSTOMER_SERVICE],
  },
  {
    id: 'cs.orders.new',
    label: '创建工单',
    routeBase: '/orders/new',
    iconName: 'PlusCircle',
    breadcrumbLabel: '创建工单',
    menuSection: 'workflow',
    status: 'implemented',
    menuOrder: 20,
    menuRoles: [Role.CUSTOMER_SERVICE],
    requiredPermission: 'order:create',
  },
  {
    id: 'cs.orders',
    label: '我的工单',
    routeBase: '/orders',
    iconName: 'ClipboardList',
    breadcrumbLabel: '我的工单',
    menuSection: 'workflow',
    status: 'implemented',
    menuOrder: 30,
    menuRoles: [Role.CUSTOMER_SERVICE],
    requiredPermission: 'order:view:self',
  },
  {
    id: 'cs.performance',
    label: '我的业绩',
    routeBase: '#',
    iconName: 'TrendingUp',
    breadcrumbLabel: '我的业绩',
    menuSection: 'finance',
    status: 'placeholder',
    menuOrder: 40,
    menuRoles: [Role.CUSTOMER_SERVICE],
    requiredPermission: 'salary:view:self',
  },
  {
    id: 'cs.salary',
    label: '我的工资单',
    routeBase: '#',
    iconName: 'Sparkles',
    breadcrumbLabel: '我的工资单',
    menuSection: 'finance',
    status: 'placeholder',
    menuOrder: 50,
    menuRoles: [Role.CUSTOMER_SERVICE],
    requiredPermission: 'salary:view:self',
  },
  {
    id: 'cs.quote',
    label: '报价查询',
    routeBase: '#',
    iconName: 'FileText',
    breadcrumbLabel: '报价查询',
    menuSection: 'workflow',
    status: 'placeholder',
    menuOrder: 60,
    menuRoles: [Role.CUSTOMER_SERVICE],
    requiredPermission: 'order:create',
  },
] as const;

export function getAdminModulesForRole(role: Role): AdminModuleMetadata[] {
  return ADMIN_MODULES
    .filter((module) => module.menuRoles.includes(role))
    .sort((a, b) => a.menuOrder - b.menuOrder);
}
