import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { NextRequest } from 'next/server';
import type { NextAuthRequest } from 'next-auth';
import { UnauthorizedError } from '@/lib/auth/errors';
import { Role } from '@/generated/prisma/enums';

const mocks = vi.hoisted(() => ({
  session: vi.fn(), order: vi.fn(), mode: vi.fn(), html: vi.fn(), render: vi.fn(),
  enqueue: vi.fn(), wait: vi.fn(), read: vi.fn(), direct: vi.fn(),
}));
vi.mock('@/lib/auth/config', () => ({ auth: (handler: unknown) => handler }));
vi.mock('@/lib/auth/session', () => ({ requireVerifiedSession: mocks.session }));
vi.mock('@/lib/order/print-view', () => ({ getOrderForPrint: mocks.order }));
vi.mock('@/lib/public-base-url', () => ({ derivePublicBaseUrl: async () => 'https://erp.example.com' }));
vi.mock('@/lib/settings', () => ({ getSetting: async () => ({ name: '测试工厂' }) }));
vi.mock('@/lib/background-jobs/mode', () => ({ backgroundJobsMode: mocks.mode }));
vi.mock('@/lib/order/print-html', async (original) => ({
  ...await original<typeof import('@/lib/order/print-html')>(), buildPrintHtml: mocks.html,
}));
vi.mock('@/lib/pdf/direct', () => ({ renderDirectOrderPdf: mocks.direct }));
vi.mock('@/lib/background-jobs/pdf', () => ({
  enqueueOrderPdfJob: mocks.enqueue, waitForOrderPdfJob: mocks.wait,
  readPdfArtifact: mocks.read,
}));

import { handleOrderPdfGet } from '@/app/api/orders/[id]/pdf/handler';

const request = (query = '') => handleOrderPdfGet(Object.assign(new NextRequest(`https://erp.example.com/api/orders/order-1/pdf${query}`), { auth: null }) as NextAuthRequest, {
  params: Promise.resolve({ id: 'order-1' }),
});

beforeEach(() => {
  vi.resetAllMocks();
  vi.stubEnv('PDF_ORDER_MODE', 'queued');
  vi.stubEnv('BACKGROUND_JOBS_MODE', 'durable');
  mocks.direct.mockImplementation(async (input) => mocks.render({ html: await input.html(), signal: input.signal }));
  mocks.session.mockResolvedValue({ user: { id: 'admin-1', role: Role.ADMIN } });
  mocks.order.mockResolvedValue({ id: 'order-1', orderNo: 'GD-001', externalSalesName: '外销甲', workOrderVersion: 3, items: [] });
  mocks.mode.mockReturnValue('inline');
  mocks.html.mockResolvedValue('<html>ready</html>');
  mocks.render.mockResolvedValue(Buffer.from('pdf'));
  mocks.enqueue.mockResolvedValue('job-1');
  mocks.wait.mockResolvedValue({ status: 'timeout' });
});

afterEach(() => vi.unstubAllEnvs());

describe('order PDF route', () => {
  it('does not return generated bytes after account revocation', async () => {
    mocks.session.mockResolvedValueOnce({ user: { id: 'admin-1', role: Role.ADMIN } }).mockRejectedValueOnce(new UnauthorizedError());
    const response = await request();
    expect(response.status).toBe(401);
    expect(response.headers.get('Content-Type')).not.toBe('application/pdf');
  });
  it('does not return generated bytes after losing resource access', async () => {
    mocks.order.mockResolvedValueOnce({ id: 'order-1', workOrderVersion: 3, items: [] }).mockResolvedValueOnce(null);
    expect((await request()).status).toBe(404);
  });

  it('serves explicit inline PDFs and preserves inline view while polling', async () => {
    expect((await request('?view=inline')).headers.get('Content-Disposition')).toMatch(/^inline;/);
    mocks.mode.mockReturnValue('durable');
    const response = await request('?view=inline');
    expect(response.status).toBe(202);
    expect(await response.text()).toContain('view=inline&amp;jobId=job-1');
  });
  it.each(['?view=bad', '?view=inline&view=inline'])('rejects ambiguous PDF presentation %s', async (query) => {
    expect((await request(query)).status).toBe(400);
    expect(mocks.order).not.toHaveBeenCalled();
  });

  it('requires authentication before disclosing order information', async () => {
    mocks.session.mockRejectedValue(new UnauthorizedError());
    expect((await request()).status).toBe(401);
    expect(mocks.order).not.toHaveBeenCalled();
  });

  it('returns 404 for an inaccessible order', async () => {
    mocks.order.mockResolvedValue(null);
    expect((await request()).status).toBe(404);
    expect(mocks.render).not.toHaveBeenCalled();
  });

  it.each(['?mode=tasks', '?mode=invalid', '?mode=order&mode=tasks'])('rejects invalid or ambiguous mode %s', async (query) => {
    const response = await request(query);
    expect(response.status).toBe(400);
    expect(await response.json()).toEqual({ error: 'Invalid print mode' });
    expect(mocks.enqueue).not.toHaveBeenCalled();
  });

  it.each(['', '?mode=order'])('renders only the production order (%s)', async (query) => {
    const response = await request(query);
    expect(response.status).toBe(200);
    expect(response.headers.get('content-type')).toBe('application/pdf');
    expect(mocks.html).toHaveBeenCalledWith(expect.anything(), { factoryName: '测试工厂' });
    expect(decodeURIComponent(response.headers.get('content-disposition') ?? '')).toContain('_外销甲.pdf');
  });

  it('binds a queued PDF to the actor, order and version on retries', async () => {
    mocks.mode.mockReturnValue('durable');
    const response = await request();
    expect(response.status).toBe(202);
    expect(mocks.enqueue).toHaveBeenCalledWith(expect.objectContaining({ orderId: 'order-1', expectedWorkOrderVersion: 3 }));
    expect(mocks.wait).toHaveBeenCalledWith('job-1', expect.objectContaining({
      expected: { orderId: 'order-1', actorId: 'admin-1', actorRole: Role.ADMIN, workOrderVersion: 3, snapshotKey: expect.any(String) },
    }));
    expect(response.headers.get('refresh')).toBeNull();
    expect(await response.text()).toContain("url.searchParams.set('status', '1')");
  });

  it('retries a failed PDF without reusing its failed job', async () => {
    mocks.mode.mockReturnValue('durable');
    mocks.wait.mockResolvedValue({ status: 'failed', errorCode: 'PrintLayoutOverflowError' });
    const response = await request('?jobId=job-old');
    expect(response.status).toBe(500);
    const html = await response.text();
    expect(html).toContain('href="/api/orders/order-1/pdf?regenerate=1"');
    expect(html).not.toContain('job-old');
    expect(mocks.enqueue).not.toHaveBeenCalled();
  });

  it('discards a PDF if the work order changed during rendering', async () => {
    mocks.order.mockResolvedValueOnce({ id: 'order-1', orderNo: 'GD-001', workOrderVersion: 3, items: [] })
      .mockResolvedValueOnce({ id: 'order-1', workOrderVersion: 4 });
    const response = await request();
    expect(response.status).toBe(409);
    expect(await response.text()).toContain('href="/api/orders/order-1/pdf?regenerate=1"');
  });

  it.each(['inline', 'durable'])('discards a PDF when access is revoked during %s rendering', async (mode) => {
    mocks.mode.mockReturnValue(mode);
    mocks.wait.mockResolvedValue({ status: 'ready', artifactName: 'job-1.pdf' });
    mocks.read.mockResolvedValue(Buffer.from('pdf'));
    mocks.order.mockResolvedValueOnce({ id: 'order-1', orderNo: 'GD-001', workOrderVersion: 3, items: [] })
      .mockResolvedValueOnce(null);
    const response = await request();
    expect(response.status).toBe(404);
    expect(await response.json()).toEqual({ error: 'Not found' });
    expect(response.headers.get('content-type')).not.toBe('application/pdf');
  });
});

it('does not return renderer diagnostics or durable error payloads', async () => {
  const diagnostic = '/private/db/password=secret https://internal.example';
  mocks.render.mockRejectedValue(new Error(diagnostic));
  const response = await request();
  expect(response.status).toBe(500);
  const inlineBody = await response.text();
  expect(inlineBody).toContain('PDF_GENERATION_FAILED');
  expect(inlineBody).not.toContain(diagnostic);
  expect(inlineBody).toContain('/print/orders/order-1');
  mocks.mode.mockReturnValue('durable');
  mocks.wait.mockResolvedValue({ status: 'failed', errorCode: diagnostic });
  const queued = await request('?jobId=job-1');
  expect(queued.status).toBe(500);
  const body = await queued.text();
  expect(body).not.toContain(diagnostic);
  expect(body).toContain('PDF_GENERATION_FAILED');
});

it('passes request auth for verification and uses the verified actor for scope and jobs', async () => {
  const authSession = { user: { id: 'old-token', role: Role.ADMIN }, expires: '2099-01-01' };
  mocks.session.mockResolvedValue({ user: { id: 'worker-1', role: Role.WORKER } });
  mocks.mode.mockReturnValue('durable');
  const req = Object.assign(new NextRequest('https://erp.example.com/api/orders/order-1/pdf'), { auth: authSession }) as NextAuthRequest;
  await handleOrderPdfGet(req, { params: Promise.resolve({ id: 'order-1' }) });
  expect(mocks.session).toHaveBeenCalledWith(authSession);
  expect(mocks.order).toHaveBeenCalledWith('order-1', { id: 'worker-1', role: Role.WORKER }, 'https://erp.example.com');
  expect(mocks.wait).toHaveBeenCalledWith('job-1', expect.objectContaining({ expected: { orderId: 'order-1', actorId: 'worker-1', actorRole: Role.WORKER, workOrderVersion: 3, snapshotKey: expect.any(String) } }));
});


it.each(['unavailable', 'delayed'])('stops automatic refresh for %s but preserves the authorized job', async (status) => {
  mocks.mode.mockReturnValue('durable');
  mocks.wait.mockResolvedValue({ status });
  const response = await request('?view=inline&jobId=job-old');
  expect(response.status).toBe(503);
  expect(response.headers.get('refresh')).toBeNull();
  const body = await response.text();
  expect(body).not.toContain('http-equiv="refresh"');
  expect(body).toContain('jobId=job-old');
  expect(body).toContain('view=inline');
  expect(body).not.toContain('regenerate=1');
  expect(mocks.enqueue).not.toHaveBeenCalled();
});

it('offers an authorized web-print fallback and an operator entry when the worker is offline', async () => {
  mocks.mode.mockReturnValue('durable');
  mocks.wait.mockResolvedValue({ status: 'unavailable' });
  const response = await request();
  const body = await response.text();
  expect(body).toContain('href="/print/orders/order-1"');
  expect(body).toContain('href="/orders/order-1"');
  expect(body).toContain('/owner/background-jobs');
  expect(body).toContain('PDF_WORKER_UNAVAILABLE');
});

it('polls the same authorized task as private JSON without enqueueing a new task', async () => {
  mocks.mode.mockReturnValue('durable');
  mocks.wait.mockResolvedValue({ status: 'timeout', phase: 'running' });
  const response = await request('?jobId=job-1&status=1&view=inline');
  expect(response.status).toBe(202);
  expect(response.headers.get('cache-control')).toBe('private, no-store');
  expect(await response.json()).toMatchObject({ state: 'pending', title: 'PDF 正在生成' });
  expect(mocks.enqueue).not.toHaveBeenCalled();
});

it.each(['?status=bad', '?status=1', '?status=1&status=1&jobId=job-1'])('rejects an invalid polling request %s', async (query) => {
  mocks.mode.mockReturnValue('durable');
  expect((await request(query)).status).toBe(400);
  expect(mocks.enqueue).not.toHaveBeenCalled();
});
it('does not expose operator actions to a worker and still rechecks access before reporting ready', async () => {
  mocks.mode.mockReturnValue('durable');
  mocks.session.mockResolvedValue({ user: { id: 'worker-1', role: Role.WORKER } });
  mocks.wait.mockResolvedValue({ status: 'unavailable' });
  expect(await (await request()).text()).not.toContain('/owner/background-jobs');
  mocks.wait.mockResolvedValue({ status: 'ready', artifactName: 'job.pdf' });
  mocks.read.mockResolvedValue(Buffer.from('pdf'));
  mocks.order.mockResolvedValueOnce({ id: 'order-1', workOrderVersion: 3, items: [] }).mockResolvedValueOnce(null);
  expect((await request('?status=1&jobId=job-1')).status).toBe(404);
});
it('returns ready JSON only after download checks, without exposing artifact names or bytes', async () => {
  mocks.mode.mockReturnValue('durable');
  mocks.wait.mockResolvedValue({ status: 'ready', artifactName: 'private.pdf' });
  mocks.read.mockResolvedValue(Buffer.from('private-pdf-bytes'));
  const response = await request('?status=1&jobId=job-1');
  expect(await response.json()).toEqual({ state: 'ready' });
  expect(mocks.session).toHaveBeenCalledTimes(2);
  expect(mocks.order).toHaveBeenCalledTimes(2);
});

it('defaults a single download to direct rendering even when workers use durable mode', async () => {
  vi.stubEnv('PDF_ORDER_MODE', '');
  mocks.mode.mockReturnValue('durable');
  const response = await request();
  expect(response.status).toBe(200);
  expect(mocks.enqueue).not.toHaveBeenCalled();
  expect(mocks.wait).not.toHaveBeenCalled();
  expect(mocks.direct).toHaveBeenCalledWith(expect.objectContaining({
    orderId: 'order-1', actorId: 'admin-1', actorRole: Role.ADMIN,
    snapshotKey: expect.any(String), regenerate: false,
  }));
  expect(response.headers.get('cache-control')).toBe('private, no-store');
  expect(response.headers.get('x-content-type-options')).toBe('nosniff');
});

it('preserves existing authorized task links after switching to direct mode', async () => {
  vi.stubEnv('PDF_ORDER_MODE', 'direct');
  mocks.mode.mockReturnValue('durable');
  expect((await request('?jobId=old-job&status=1')).status).toBe(202);
  expect(mocks.wait).toHaveBeenCalledWith('old-job', expect.anything());
  expect(mocks.direct).not.toHaveBeenCalled();
});

it.each(['?jobId=', '?jobId=a&jobId=b', '?jobId=../private'])('rejects ambiguous legacy task links %s', async (query) => {
  vi.stubEnv('PDF_ORDER_MODE', 'direct');
  mocks.mode.mockReturnValue('durable');
  expect((await request(query)).status).toBe(400);
  expect(mocks.direct).not.toHaveBeenCalled();
  expect(mocks.wait).not.toHaveBeenCalled();
});

it('discards a direct or cached PDF if content changes without a version bump', async () => {
  vi.stubEnv('PDF_ORDER_MODE', 'direct');
  const order = { id: 'order-1', orderNo: 'GD-001', workOrderVersion: 3, items: [] };
  mocks.order.mockResolvedValueOnce({ ...order, remark: 'before' }).mockResolvedValueOnce({ ...order, remark: 'after' });
  const response = await request();
  expect(response.status).toBe(409);
  expect(await response.text()).toContain('工单内容已更新');
});

it('provides a recoverable busy response without enqueueing more work', async () => {
  vi.stubEnv('PDF_ORDER_MODE', 'direct');
  mocks.direct.mockRejectedValue(Object.assign(new Error('private'), { name: 'PdfBusyError' }));
  const response = await request();
  expect(response.status).toBe(503);
  const body = await response.text();
  expect(body).toContain('PDF_BUSY');
  expect(body).toContain('网页打印');
  expect(body).not.toContain('private');
  expect(mocks.enqueue).not.toHaveBeenCalled();
});

it('refuses an invalid mode rather than silently switching execution paths', async () => {
  vi.stubEnv('PDF_ORDER_MODE', 'typo');
  expect((await request()).status).toBe(503);
  expect(mocks.direct).not.toHaveBeenCalled();
  expect(mocks.enqueue).not.toHaveBeenCalled();
});

it('fails closed when production PDF mode is missing', async () => {
  vi.stubEnv('NODE_ENV', 'production');
  vi.stubEnv('PDF_ORDER_MODE', '');
  const response = await request();
  expect(response.status).toBe(503);
  expect(await response.text()).toContain('PDF_CONFIGURATION_INVALID');
  expect(mocks.direct).not.toHaveBeenCalled();
});

it.each([Role.ADMIN, Role.SALES, Role.WORKER])('returns %s to an accessible order page from a PDF failure', async role => {
  mocks.session.mockResolvedValue({ user: { id: 'user', role } });
  mocks.mode.mockReturnValue('durable');
  mocks.wait.mockResolvedValue({ status: 'unavailable' });
  const response = await request();
  const html = await response.text();
  expect(html).toContain(`href="${role === Role.WORKER ? '/worker/orders' : '/orders'}/order-1">返回工单`);
  if (role === Role.WORKER) expect(html).not.toContain('href="/orders/order-1"');
});
